const STORAGE_KEY='impec-reports-v1';
const SETTINGS_KEY='impec-settings-v1';
const defaultSettings={company:'SARL IMPEC',technician:'Pascal Valette',client:'MAC CORMICK',sector:'Salé',senderEmail:'',ccEmail:'',aiEndpoint:'/api/reformulate',contacts:[]};
const state={reports:[],settings:{...defaultSettings},current:null,screen:'homeScreen',recognition:null,listening:false,dictationMode:'native'};
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const nowIso=()=>new Date().toISOString();
const formatDate=value=>new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:value?.includes('T')?'short':undefined}).format(new Date(value));
const escapeHtml=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const textToHtml=value=>escapeHtml(value).replace(/\n/g,'<br>');

function normalizeSettings(saved={}){const settings={...defaultSettings,...saved};settings.contacts=Array.isArray(saved.contacts)?saved.contacts:[];if(saved.recipientEmail&&!settings.contacts.some(contact=>contact.email.toLowerCase()===saved.recipientEmail.toLowerCase()))settings.contacts.push({id:uid(),name:'Responsable',email:saved.recipientEmail});return settings}
function load(){
  try{state.reports=JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{state.reports=[]}
  try{state.settings=normalizeSettings(JSON.parse(localStorage.getItem(SETTINGS_KEY))||{})}catch{state.settings=normalizeSettings()}
}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.reports));$('#saveState').textContent='Sauvegardé'}
function persistSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings))}
function blankReport(){return{id:uid(),createdAt:nowIso(),updatedAt:nowIso(),closedAt:null,sentAt:null,status:'BROUILLON',version:1,shift:'',site:'',machine:'',number:'',recipientEmail:state.settings.contacts[0]?.email||'',ccEmail:state.settings.ccEmail||'',rawText:'',observation:'',diagnosis:'',work:'',parts:'',tests:'',notes:'',photos:[],history:[]}}
function showScreen(id,title){$$('.screen').forEach(el=>el.classList.toggle('active',el.id===id));state.screen=id;$('#screenTitle').textContent=title;$('#backButton').classList.toggle('hidden',id==='homeScreen');scrollTo({top:0,behavior:'instant'})}
function updateNetwork(){const online=navigator.onLine;$('#networkBadge').textContent=online?'En ligne':'Hors ligne';$('#networkBadge').classList.toggle('online',online)}
function newReport(){state.current=blankReport();state.reports.unshift(state.current);persist();fillEditor();showScreen('editorScreen','Nouveau rapport')}
function renderRecipientOptions(){const select=$('#recipientSelect');const current=state.current?.recipientEmail||'';select.innerHTML='<option value="">Choisir un destinataire</option>'+state.settings.contacts.map(contact=>`<option value="${escapeHtml(contact.email)}">${escapeHtml(contact.name)} — ${escapeHtml(contact.email)}</option>`).join('');if(current&&!state.settings.contacts.some(contact=>contact.email===current))select.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(current)}">${escapeHtml(current)}</option>`);select.value=current||''}
function fillEditor(){const r=state.current;if(!r)return;$$('input[name="shift"]').forEach(el=>el.checked=el.value===r.shift);$('#siteInput').value=r.site;$('#machineInput').value=r.machine;$('#numberInput').value=r.number;renderRecipientOptions();$('#ccInput').value=r.ccEmail||state.settings.ccEmail||'';$('#rawTextInput').value=r.rawText;$$('[data-field]').forEach(el=>el.value=r[el.dataset.field]||'');$('#reportStatus').textContent=`${r.status} · V${r.version}`;renderPhotos()}
function saveEditor(){const r=state.current;if(!r)return;r.shift=$('input[name="shift"]:checked')?.value||'';r.site=$('#siteInput').value.trim();r.machine=$('#machineInput').value.trim();r.number=$('#numberInput').value.trim();r.recipientEmail=$('#recipientSelect').value||r.recipientEmail||'';r.ccEmail=$('#ccInput').value.trim()||state.settings.ccEmail||'';r.rawText=$('#rawTextInput').value.trim();$$('[data-field]').forEach(el=>r[el.dataset.field]=el.value.trim());r.updatedAt=nowIso();$('#saveState').textContent='Sauvegarde…';persist()}
function renderPhotos(){const r=state.current;$('#photoCount').textContent=r.photos.length;$('#photoList').innerHTML=r.photos.map((p,i)=>`<div class="photo-card"><img src="${p.data}" alt="Photo ${i+1}"><input data-caption="${i}" value="${escapeHtml(p.caption)}" placeholder="Légende facultative"><button data-remove-photo="${i}">Supprimer</button></div>`).join('')}
async function compressPhoto(file){const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=data});const max=1600;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return{data:canvas.toDataURL('image/jpeg',.78),caption:'',name:file.name}}
async function addPhotos(files){for(const file of files){try{state.current.photos.push(await compressPhoto(file))}catch(e){alert(`Photo impossible à importer : ${file.name}`)}}saveEditor();renderPhotos()}
function setupDictation(){
  const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
  const isStandalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
  const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
  // WebKit expose parfois l'API sans qu'elle fonctionne dans une PWA installée.
  if(!SpeechRecognition||(isIOS&&isStandalone)){
    state.dictationMode='native';
    $('#dictateLabel').textContent='Ouvrir la dictée iPhone';
    $('#dictationHelp').textContent='Touchez ce bouton, puis le micro du clavier iPhone.';
    return;
  }
  try{
    const recognition=new SpeechRecognition();
    recognition.lang='fr-FR';recognition.continuous=true;recognition.interimResults=true;
    let base='';
    recognition.onstart=()=>{state.listening=true;base=$('#rawTextInput').value.trim();$('#dictateButton').classList.add('listening');$('#dictateLabel').textContent='Arrêter la dictée';$('#dictationHelp').textContent='Je vous écoute…'};
    recognition.onresult=event=>{let finalText='',interim='';for(let i=event.resultIndex;i<event.results.length;i++){const text=event.results[i][0].transcript;if(event.results[i].isFinal)finalText+=`${text} `;else interim+=text}if(finalText)base=`${base} ${finalText}`.trim();$('#rawTextInput').value=`${base}${interim?' '+interim:''}`;saveEditor()};
    recognition.onend=()=>{state.listening=false;$('#dictateButton').classList.remove('listening');$('#dictateLabel').textContent='Dicter l’intervention';$('#dictationHelp').textContent='';saveEditor()};
    recognition.onerror=e=>{state.listening=false;$('#dictateButton').classList.remove('listening');state.dictationMode='native';$('#dictateLabel').textContent='Ouvrir la dictée iPhone';$('#dictationHelp').textContent='La reconnaissance intégrée est indisponible. Touchez le micro du clavier iPhone.';$('#aiMessage').textContent=e.error==='not-allowed'?'Autorisez le microphone, ou utilisez le micro du clavier iPhone.':'La dictée directe est indisponible sur cet appareil. Votre rapport reste sauvegardé.'};
    state.recognition=recognition;state.dictationMode='webspeech';
  }catch{state.dictationMode='native';$('#dictateLabel').textContent='Ouvrir la dictée iPhone';$('#dictationHelp').textContent='Touchez ce bouton, puis le micro du clavier iPhone.'}
}
function openNativeDictation(){const input=$('#rawTextInput');input.focus({preventScroll:false});input.setSelectionRange(input.value.length,input.value.length);$('#dictationHelp').textContent='Le clavier est ouvert : touchez son bouton micro pour parler.'}
function toggleDictation(){if(state.dictationMode==='native'||!state.recognition){openNativeDictation();return}try{if(state.listening)state.recognition.stop();else state.recognition.start()}catch{state.dictationMode='native';openNativeDictation()}}
async function reformulate(){saveEditor();const raw=state.current.rawText;if(!raw){$('#aiMessage').textContent='Dictez ou saisissez d’abord votre intervention.';return}if(!navigator.onLine){$('#aiMessage').textContent='Texte conservé. La reformulation nécessite une connexion.';return}$('#reformulateButton').disabled=true;$('#aiMessage').textContent='Reformulation en cours…';try{const response=await fetch(state.settings.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:raw,sections:['observation','diagnosis','work','parts','tests','notes']})});if(!response.ok)throw new Error('service indisponible');const result=await response.json();['observation','diagnosis','work','parts','tests','notes'].forEach(key=>{if(typeof result[key]==='string')state.current[key]=result[key]});fillEditor();persist();$('#aiMessage').textContent='Reformulation terminée. Vérifiez les informations techniques.'}catch{$('#aiMessage').textContent='IA non configurée ou indisponible. La dictée originale est conservée sans perte.'}finally{$('#reformulateButton').disabled=false}}
function closeReport(){saveEditor();openConfirm('Clôturer le rapport','Le rapport restera modifiable. Toute correction ultérieure créera automatiquement une nouvelle version.',()=>{state.current.status='CLÔTURÉ';state.current.closedAt=nowIso();state.current.history.push({action:'cloture',date:nowIso(),version:state.current.version});persist();fillEditor();renderPreview();showScreen('previewScreen','Rapport clôturé')})}
function ensureRevision(){if(state.current.status==='BROUILLON')return;state.current.history.push({action:'revision',date:nowIso(),fromVersion:state.current.version});state.current.version+=1;state.current.status='BROUILLON';state.current.closedAt=null;persist()}
function renderReports(query=''){const q=query.toLocaleLowerCase('fr');const items=state.reports.filter(r=>[r.machine,r.site,r.rawText,r.status,formatDate(r.createdAt)].join(' ').toLocaleLowerCase('fr').includes(q));$('#reportsList').innerHTML=items.length?items.map(r=>`<article class="report-item"><h3>${escapeHtml(r.machine||'Machine non renseignée')}</h3><p>${formatDate(r.createdAt)} · ${escapeHtml(r.shift||'Horaire non choisi')}</p><p>${escapeHtml(r.site||'Site non renseigné')} · ${r.status} · V${r.version}</p><div class="item-actions"><button data-open="${r.id}">Ouvrir</button><button data-preview="${r.id}">PDF</button></div></article>`).join(''):'<div class="card"><p>Aucun rapport trouvé.</p></div>'}
function openReport(id,preview=false){state.current=state.reports.find(r=>r.id===id);if(!state.current)return;if(preview){renderPreview();showScreen('previewScreen','Aperçu du rapport')}else{ensureRevision();fillEditor();showScreen('editorScreen',state.current.machine||'Modifier le rapport')}}
function renderPreview(){saveEditor();const r=state.current;const s=state.settings;const sections=[['Constat',r.observation],['Diagnostic',r.diagnosis],['Intervention',r.work],['Pièces remplacées',r.parts],['Essais / Résultat',r.tests],['Remarques',r.notes]].filter(([,v])=>v);$('#printReport').innerHTML=`<header><p class="eyebrow">${escapeHtml(s.company)}</p><h1>Rapport d’intervention technique</h1><p>Sous-traitance pour ${escapeHtml(s.client)} · Secteur ${escapeHtml(s.sector)}</p></header><div class="report-meta"><strong>Technicien</strong><span>${escapeHtml(s.technician)}</span><strong>Date</strong><span>${formatDate(r.createdAt)}</span><strong>Horaire</strong><span>${escapeHtml(r.shift||'Non renseigné')}</span><strong>Site</strong><span>${escapeHtml(r.site||'Non renseigné')}</span><strong>Machine</strong><span>${escapeHtml(r.machine||'Non renseignée')}</span><strong>N° intervention</strong><span>${escapeHtml(r.number||'Non renseigné')}</span><strong>Version</strong><span>V${r.version}</span></div>${sections.map(([title,value])=>`<section><h2>${title}</h2><div>${textToHtml(value)}</div></section>`).join('')}${!sections.length&&r.rawText?`<section><h2>Compte rendu dicté</h2><div>${textToHtml(r.rawText)}</div></section>`:''}${r.photos.length?`<section><h2>Photos</h2>${r.photos.map((p,i)=>`<figure class="report-photo"><img src="${p.data}" alt="Photo ${i+1}">${p.caption?`<figcaption>${escapeHtml(p.caption)}</figcaption>`:''}</figure>`).join('')}</section>`:''}<footer><p>Rapport ${escapeHtml(r.status.toLowerCase())} · créé le ${formatDate(r.createdAt)}${r.closedAt?` · clôturé le ${formatDate(r.closedAt)}`:''}</p></footer>`}
function shareText(){const r=state.current;return`Rapport d’intervention – ${new Date(r.createdAt).toLocaleDateString('fr-FR')} – ${r.machine||'Équipement'} – ${state.settings.technician}`}
async function shareReport(){if(navigator.share){try{await navigator.share({title:shareText(),text:`${shareText()}\nOuvrez l’aperçu puis utilisez « Créer / imprimer le PDF » pour joindre le document.`})}catch{}}else{alert('Le partage direct n’est pas disponible. Utilisez la création PDF puis le bouton de partage du système.')}}
function emailReport(){const recipient=state.current.recipientEmail;if(!recipient){alert('Choisissez un destinataire dans le rapport.');return}const cc=state.current.ccEmail||state.settings.ccEmail||'';const subject=encodeURIComponent(shareText());const body=encodeURIComponent('Bonjour,\n\nVeuillez trouver le rapport d’intervention en pièce jointe.\n\nCordialement,\n'+state.settings.technician);location.href=`mailto:${encodeURIComponent(recipient)}?cc=${encodeURIComponent(cc)}&subject=${subject}&body=${body}`;state.current.sentAt=nowIso();state.current.status='ENVOYÉ';state.current.history.push({action:'envoi_prepare',date:nowIso(),version:state.current.version,recipient,cc});persist()}
function renderContacts(){$('#contactsList').innerHTML=state.settings.contacts.map(contact=>`<div class="contact-item"><div><strong>${escapeHtml(contact.name)}</strong><span>${escapeHtml(contact.email)}</span></div><button data-remove-contact="${contact.id}">Supprimer</button></div>`).join('')}
function fillSettings(){$$('[data-setting]').forEach(el=>el.value=state.settings[el.dataset.setting]||'');renderContacts()}
function saveSettings(){$$('[data-setting]').forEach(el=>state.settings[el.dataset.setting]=el.value.trim());persistSettings();alert('Paramètres enregistrés.')}
function addContact(){const name=$('#contactNameInput').value.trim();const email=$('#contactEmailInput').value.trim();if(!name||!email||!email.includes('@')){alert('Indiquez un nom et une adresse e-mail valide.');return}if(state.settings.contacts.some(contact=>contact.email.toLowerCase()===email.toLowerCase())){alert('Cette adresse existe déjà.');return}state.settings.contacts.push({id:uid(),name,email});persistSettings();$('#contactNameInput').value='';$('#contactEmailInput').value='';renderContacts()}
function exportBackup(){const blob=new Blob([JSON.stringify({version:1,exportedAt:nowIso(),settings:state.settings,reports:state.reports},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sauvegarde-interventions-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importBackup(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.reports))throw new Error();openConfirm('Restaurer la sauvegarde',`${data.reports.length} rapport(s) remplaceront les données actuellement stockées sur cet appareil.`,()=>{state.reports=data.reports;state.settings=normalizeSettings(data.settings||{});persist();persistSettings();fillSettings();alert('Sauvegarde restaurée.')})}catch{alert('Fichier de sauvegarde invalide.')}}
function openConfirm(title,text,onConfirm){const dialog=$('#confirmDialog');$('#dialogTitle').textContent=title;$('#dialogText').textContent=text;dialog.onclose=()=>{if(dialog.returnValue==='confirm')onConfirm()};dialog.showModal()}
function goBack(){if(state.screen==='editorScreen')saveEditor();if(state.screen==='previewScreen'&&state.current){fillEditor();showScreen('editorScreen',state.current.machine||'Rapport')}else showScreen('homeScreen','Interventions')}

function bind(){
  $('#newReportButton').onclick=newReport;$('#reportsButton').onclick=()=>{renderReports();showScreen('reportsScreen','Mes rapports')};$('#settingsButton').onclick=()=>{fillSettings();showScreen('settingsScreen','Paramètres')};$('#backButton').onclick=goBack;$('#dictateButton').onclick=toggleDictation;$('#reformulateButton').onclick=reformulate;$('#photoInput').onchange=e=>addPhotos(e.target.files);$('#previewButton').onclick=()=>{renderPreview();showScreen('previewScreen','Aperçu du rapport')};$('#closeReportButton').onclick=closeReport;$('#printButton').onclick=()=>print();$('#shareButton').onclick=shareReport;$('#emailButton').onclick=emailReport;$('#saveSettingsButton').onclick=saveSettings;$('#addContactButton').onclick=addContact;$('#exportButton').onclick=exportBackup;$('#importInput').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$('#searchInput').oninput=e=>renderReports(e.target.value);
  $('#editorScreen').addEventListener('input',e=>{if(e.target.matches('input,textarea')&&!e.target.matches('[data-caption]'))saveEditor()});
  $('#photoList').onclick=e=>{const i=e.target.dataset.removePhoto;if(i!==undefined){state.current.photos.splice(Number(i),1);persist();renderPhotos()}};
  $('#photoList').oninput=e=>{const i=e.target.dataset.caption;if(i!==undefined){state.current.photos[Number(i)].caption=e.target.value;persist()}};
  $('#reportsList').onclick=e=>{if(e.target.dataset.open)openReport(e.target.dataset.open);if(e.target.dataset.preview)openReport(e.target.dataset.preview,true)};
  $('#contactsList').onclick=e=>{const id=e.target.dataset.removeContact;if(!id)return;state.settings.contacts=state.settings.contacts.filter(contact=>contact.id!==id);persistSettings();renderContacts()};
  addEventListener('online',updateNetwork);addEventListener('offline',updateNetwork);addEventListener('beforeunload',saveEditor)
}
load();bind();setupDictation();updateNetwork();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
